resources:
  pipelines:
  - pipeline: pipeline-trigger
    source: Build_And_Push_All
    trigger: true

trigger:
  branches:
    include:
    - dev
    - release/*
    - linkathon/*
  paths:
    include:
    - DotNet/Admin.BFF/*
    - DotNet/Shared/*
    - DotNet/Link.Authorization/*
    exclude:
    - '*'

pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: link-cloud-variables
- name: project
  value: 'DotNet/Admin.BFF/Admin.BFF.csproj'
- name: registryRepositoryName
  value: 'link-admin'
- name: dockerPath
  value: '**/DotNet/Admin.BFF/Dockerfile'
- name: serviceName
  value: 'Admin.BFF'
- name: projectDir
  value: 'DotNet/Admin.BFF'

steps:
  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
      projects: '$(project)'

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        GIT_COMMIT=$(git rev-parse --short HEAD)
        echo "GIT_COMMIT: ${GIT_COMMIT}"
        echo "##vso[task.setvariable variable=GIT_COMMIT]${GIT_COMMIT}"
        
  - task: PythonScript@0
    displayName: "Inject Service Info"
    inputs:
      scriptSource: 'filePath'
      scriptPath: '$(Build.SourcesDirectory)/Scripts/set_service_info.py'
      workingDirectory: '$(Build.SourcesDirectory)'
      arguments: './ "$(projectDir)" "$(GIT_COMMIT)" "$(Build.BuildNumber)"'
  
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: build
      projects: '$(project)'

  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        if ("$(Build.SourceBranch)" -like "*release/*") {
        $myTag1 = "release-$(Build.SourceBranchName)-$(GIT_COMMIT)"
        }
        else { 
        $myTag1 = "$(Build.SourceBranchName)-$(GIT_COMMIT)"
        }
        Write-Host "##vso[task.setvariable variable=MyTag]$myTag1"
        Write-Host "Set MyTag to: $myTag1"  

  - task: Docker@2
    displayName: "Build & Push Docker Image"
    condition: always()
    inputs:
      containerRegistry: $(containerRegistry) # Variable Group
      repository: $(registryRepositoryName)
      command: 'buildAndPush'
      Dockerfile: $(dockerPath)
      tags: |
        latest
        $(MyTag)
      buildContext: '$(Build.Repository.LocalPath)'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)'
      artifact: 'manifest'
