name: "Build, Run, E2E Tests"

on:
#  schedule:
#    - cron: "0 0 * * *"
  pull_request:
    branches:
      - dev
  merge_group:
    branches:
      - dev

jobs:
  skip_if_only_docs:
    runs-on: ubuntu-latest
    outputs:
      only_docs: ${{ steps.changes.outputs.only_docs }}
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check for non-docs changes
        id: check_changes
        run: |
          git fetch origin ${{ github.base_ref }}
          DIFF=$(git diff --name-only origin/${{ github.base_ref }}...HEAD | grep -v '^docs/' || true)
          if [ -z "$DIFF" ]; then
            echo "Only docs changed. Skipping tests."
            echo "only_docs=true" > result.txt
          else
            echo "Changes outside docs detected."
            echo "only_docs=false" > result.txt
          fi

      - name: Set output
        id: set_output
        run: |
          ONLY_DOCS=$(cat result.txt)
          echo "only_docs=$ONLY_DOCS" >> $GITHUB_OUTPUT
          
  docker-build-and-run:
    needs: skip_if_only_docs
    if: needs.skip_if_only_docs.outputs.only_docs == 'false'
    
    runs-on: [docker-16core-64gb]

    env:
      PROJECT_NAME: link
      HEALTH_CHECK_TIMEOUT: 10
      CHECK_INTERVAL: 5

    steps:          
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build services with cache
        run: |
          docker buildx bake --file docker-compose.yml \
            --set *.cache-from=type=gha \
            --set *.cache-to=type=gha \
            --set *.output=type=docker   # <-- makes images visible to `docker compose`
      - name: Start services
        run: docker compose up --no-build -d

      - name: Wait for services to start
        run: sleep 30

      - name: Wait for Services to Become Healthy
        run: |
          chmod +x Scripts/check_health.sh
          Scripts/check_health.sh $PROJECT_NAME $HEALTH_CHECK_TIMEOUT $CHECK_INTERVAL

      - name: Run Backend E2E Tests
        run: dotnet test ./Tests/BackendE2ETests/BackendE2ETests.csproj --filter "Category=SmokeTest" --logger "trx;LogFileName=test-results.trx"
        env:
          SMOKE_TEST_DOWNLOAD_PATH: ./Tests/BackendE2ETests/TestResults/

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ./Tests/BackendE2ETests/TestResults/test-results.trx

      - name: Upload submission ZIP
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ./Tests/BackendE2ETests/TestResults/adhoc-reporting-smoke-test-submission.zip