name: "Unit Tests"

on:
  pull_request:
    branches:
      - dev
  merge_group:
    branches:
      - dev

jobs:
  dotnet-unit-tests:
    runs-on: windows-latest  # Runner environment
    timeout-minutes: 10      # Job-level timeout

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4

    - name: Cache NuGet packages
      uses: actions/cache@v4
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Restore dependencies
      run: dotnet restore DotNet/ServiceTests/ServiceTests.csproj

    - name: Build
      run: dotnet build DotNet/ServiceTests/ServiceTests.csproj --configuration Release --no-restore

    - name: Run dotnet-unit tests
      run: dotnet test DotNet/ServiceTests/ServiceTests.csproj --configuration Release --no-build --verbosity detailed --logger "trx;LogFileName=dotnet-unit-test-results.trx" --results-directory ./TestResults --filter "Category=UnitTests"
      continue-on-error: true
      timeout-minutes: 5

    - name: Debug test results
      run: dir .\TestResults
      continue-on-error: true

    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: dotnet-unit-test-results
        path: ./TestResults/*.trx

    - name: .NET Integration Test Report
      uses: dorny/test-reporter@v2
      if: always()
      with:
        name: XUnit Integration Tests
        path: ./TestResults/dotnet-unit-test-results.trx
        reporter: dotnet-trx

  java-unit-tests:
    runs-on: ['ubuntu-latest']
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
      
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      
      - name: Build and Test with Maven
        run: mvn clean test
        working-directory: Java

      - name: Java Unit Test Report
        uses: dorny/test-reporter@v2
        if: always()
        with:
          name: XUnit Tests
          path: "**/surefire-reports/*.xml"
          reporter: java-junit