loki:
  enabled: false
  url: ''
  app: link-cloud

server:
  port: 31820

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false


spring:
  application:
    name: ValidationService
  jackson:
    mapper:
      accept-case-insensitive-enums: true
      accept-case-insensitive-properties: true
  mvc:
    problemdetails:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ''
  #datasource:
  #  url: jdbc:sqlserver://;serverName=localhost\SQLEXPRESS;encrypt=true;trustServerCertificate=true
  #  username: link-user
  #  password: link-password
  kafka:
    bootstrap-servers: ''
    consumer:
      group-id: validation
    producer:
      client-id: validation-service
    #properties:
      #security.protocol: SASL_SSL
      #sasl.mechanism: PLAIN
      #sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="$ConnectionString" password="";
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

secret-management:
  key-vault-uri: ''

authentication:
  anonymous: false
  authority: ''

link:
  report:
    base-url: http://localhost:5110
    routes:
      submission-bundle:
        path: /api/Report/Bundle/Patient
        query:
          - facilityId={facilityId}
          - patientId={patientId}
          - reportScheduleId={reportId}
